### ISSUE TITLE
Build fail 0.2.17-alt15

### ISSUE THREAD

**Issue by Pro-pra** [august-alt/gpui#19]
Happy New Year!

Attemp build on Rosa fail: 

> DEBUG: /builddir/build/BUILD/gpui-0.2.17/src/plugins/preferences/folder_options/folderoptionscontaineritem.inl: In constructor 'preferences::FolderOptionsContainerItem<FolderOptionItem>::FolderOptionsContainerItem()':
> DEBUG: /builddir/build/BUILD/gpui-0.2.17/src/plugins/preferences/folder_options/folderoptionscontaineritem.inl:32:38: error: 'class preferences::CommonItem' has no member named 'setVisible'
> DEBUG:    32 |     addProperty<CommonItem>(COMMON)->setVisible(false);

full log https://file-store.rosalinux.ru/api/v1/file_stores/0fc1a44e15a2cc95f113b994b10e7c6a47e1d9f5.log?show=true
qt5 version 5.15.5
i attempt add to files:
`#include <QWidget>` not help me

**Comment by Pro-pra** [comment]
первая проблема закрыта патчем:
`--- a/src/plugins/preferences/common/commonitem.h	2022-12-28 18:21:07.000000000 +0900
+++ b/src/plugins/preferences/common/commonitem.h	2022-12-30 10:08:21.950038349 +0900
@@ -22,6 +22,7 @@
 #define GPUI_COMMONITEM_H
 
 #include "basepreferenceitem.h"
+#include <QWidget>
 
 namespace preferences
 {
@@ -68,6 +69,9 @@
     bool removePolicy() const;
     void setRemovePolicy(bool state);
 
+    bool setVisible() const;
+    void setVisible(bool state);
+
     constexpr static inline const char* propertyToString(const PropertyType& type)
     {
         switch (type)`

Но осталась вторая проблема:
`DEBUG: /builddir/build/BUILD/gpui-0.2.17/src/plugins/preferences/common/preferencesmodel.cpp:60:5: error: 'registerItem' was not declared in this scope; did you mean 'register_item'?
DEBUG:    60 |     registerItem<DrivesContainerItem>();
`

**Comment by august-alt** [comment]
Hi!
Though a bit late I would also like to wish you Happy New Year! 
Unfortunately, attempts to quickly find the cause of the problem were unsuccessful. 
Rosa Linux is not supported at the moment and I don't have enough time to support this build. 
I don't know if it will be of any help but, I am going to suggest that you use a virtual machine with ALT Linux, since there exists already pre-built packages that you can install from repository.

**Comment by Pro-pra** [comment]
RESOLVED! need qt-mvvm from git. My patch also not needed.
