### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by dmulder** [august-alt/gpui#4]
```
[   25s] /usr/bin/c++ -fPIC -Wno-deprecated-declarations -fvisibility=hidden -fvisibility-inlines-hidden -pedantic -Wall -Wextra -Wno-long-long -O2 -g -DNDEBUG -flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libspol-plugin.so -o libspol-plugin.so CMakeFiles/spol-plugin.dir/spolformat.cpp.o CMakeFiles/spol-plugin.dir/spolplugin.cpp.o 
[   25s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/spol-plugin.dir/spolplugin.cpp.o: in function `gpui::SpolPlugin::SpolPlugin()':
[   25s] /home/abuild/rpmbuild/BUILD/gpui-0.1.0/src/plugins/spol/spolplugin.cpp:28: undefined reference to `gpui::Plugin::Plugin(char const*)'
[   25s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/spol-plugin.dir/spolplugin.cpp.o: in function `gpui::SpolPlugin::~SpolPlugin()':
[   25s] /home/abuild/rpmbuild/BUILD/gpui-0.1.0/src/plugins/spol/spolplugin.cpp:24: undefined reference to `gpui::Plugin::~Plugin()'
[   25s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/spol-plugin.dir/spolplugin.cpp.o: in function `gpui::SpolPlugin::~SpolPlugin()':
[   25s] /home/abuild/rpmbuild/BUILD/gpui-0.1.0/src/plugins/spol/spolplugin.cpp:24: undefined reference to `gpui::Plugin::~Plugin()'
[   25s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/spol-plugin.dir/spolplugin.cpp.o:(.data.rel.ro._ZTIN4gpui10SpolPluginE[_ZTIN4gpui10SpolPluginE]+0x10): undefined reference to `typeinfo for gpui::Plugin'
[   25s] collect2: error: ld returned 1 exit status
```

Full build results here: https://build.opensuse.org/package/live_build_log/home:dmulder:alt/gpui/openSUSE_Tumbleweed/x86_64
I'm not sure what to make of this failure. Seems there are undefined references in gpui itself?

**Comment by dmulder** [comment]
This patch resolves that particular error, but then there are more similar errors:
```
diff --git a/src/model/plugin.cpp b/src/model/plugin.cpp
index 3c220cc..34ea9c0 100644
--- a/src/model/plugin.cpp
+++ b/src/model/plugin.cpp
@@ -25,7 +25,7 @@
 
 namespace gpui {
 
-    class PluginPrivate
+    class Plugin
     {
     public:
         QString name;
@@ -59,7 +59,7 @@ namespace gpui {
     }
 
     Plugin::Plugin(const QString& name)
-        : d(new PluginPrivate())
+        : d(new Plugin())
     {
         d->name = name;
     }
diff --git a/src/model/plugin.h b/src/model/plugin.h
index 852dbdd..27ad2a3 100644
--- a/src/model/plugin.h
+++ b/src/model/plugin.h
@@ -33,7 +33,6 @@ class QLibrary;
 class QString;
 
 namespace gpui {
-    class PluginPrivate;
     class PluginStorage;
 
     class GPUI_MODEL_EXPORT Plugin
@@ -55,7 +54,7 @@ namespace gpui {
         void registerPluginClass(const QString& name, std::function<void*()> constructor);
 
     private:
-        PluginPrivate* d;
+        Plugin* d;
     };
 }
 
```

What is it that you're doing with this strange name mangling that's breaking the build?

**Comment by august-alt** [comment]
There nothing strange about this naming the purpose of this is to separate data from implementation, PluginPrivate structure holds data and Plugin class holds implementation. I've implemented build using opensuse/tumbleweed:latest docker image. Here is the link to the build log:  https://github.com/august-alt/gpui/runs/5125801369?check_suite_focus=true
As you can see everything works correctly without any changes to the code-base.

We need to investigate what causes build to break in this particular case.

**Comment by dmulder** [comment]
Strange. I'm not sure what the difference is here. The results aught to be the same.

**Comment by dmulder** [comment]
Do you see the same thing if you use -j12?
I also noticed I seem to be missing more build depends.
I just encountered that same error again, later on in the build. Sigh. Not sure what's going on here.

**Comment by dmulder** [comment]
Ok, it has something to do with the default cmake parameters passed by the build service %cmake macro. I'll narrow down which is causing the problem. I'm able to build if I remove all of those parameters.

**Comment by dmulder** [comment]
@august-alt I found it. This option breaks the build: -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--no-undefined"

**Comment by august-alt** [comment]
> @august-alt I found it. This option breaks the build: -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--no-undefined"
The last commit in the master branch should support these flags.

**Comment by dmulder** [comment]
Fixed.
