### ISSUE TITLE
The app creates two different .conf files if language is changed

### ISSUE THREAD

**Issue by Kvel2D** [august-alt/gpui#6]
QSettings instance is created using default ctor. Default ctor uses organization name in the path for .conf file. Organization name is set in main.cpp like this:

`app.setOrganizationName(QCoreApplication::translate("main", "BaseALT Ltd."));`

Because organization name is translated, settings path will be different depending on current language.

**Comment by august-alt** [comment]
Fixed in https://github.com/august-alt/gpui/commit/26d3316bae6feb4200a034df2469a371300ef332.
